import assert from "node:assert/strict";
import test from "node:test";
import { signTicketPayload, verifyTicketPayload } from "../src/server/tickets/hmac.js";

process.env.TICKET_HMAC_SECRET = "c".repeat(48);
process.env.NEXTAUTH_SECRET = "d".repeat(48);

test("check-in HMAC accepts owner tuple and rejects swaps", () => {
  const base = { registrationId: "reg-1", eventId: "fest-2026", userId: "user-9" };
  const sig = signTicketPayload(base);
  assert.equal(verifyTicketPayload({ ...base, sig }), true);
  assert.equal(verifyTicketPayload({ ...base, userId: "other", sig }), false);
  assert.equal(verifyTicketPayload({ ...base, eventId: "other-event", sig }), false);
  assert.equal(verifyTicketPayload({ ...base, registrationId: "reg-2", sig }), false);
});

test("QR pass JSON round-trip correctly decodes and validates ticket signature", () => {
  const base = { registrationId: "reg-host-xyz", eventId: "hackathon-2026", userId: "user-dev-42" };
  const sig = signTicketPayload(base);

  // Standard QR payload generated by API
  const qrRaw = JSON.stringify({
    regId: base.registrationId,
    eventId: base.eventId,
    userId: base.userId,
    sig,
  });

  const parsed = JSON.parse(qrRaw);
  const registrationId = parsed.registrationId || parsed.regId;
  assert.equal(registrationId, base.registrationId);

  const isValid = verifyTicketPayload({
    registrationId,
    eventId: parsed.eventId,
    userId: parsed.userId,
    sig: parsed.sig,
  });
  assert.equal(isValid, true);
});

test("QR pass rejects tampered signature or mismatched event", () => {
  const base = { registrationId: "reg-alpha", eventId: "summit-2026", userId: "user-101" };
  const sig = signTicketPayload(base);

  // Tampered payload trying to reuse pass on another event
  const isCrossEventValid = verifyTicketPayload({
    registrationId: base.registrationId,
    eventId: "different-event",
    userId: base.userId,
    sig,
  });
  assert.equal(isCrossEventValid, false);

  // Altered signature
  const isForgedValid = verifyTicketPayload({
    registrationId: base.registrationId,
    eventId: base.eventId,
    userId: base.userId,
    sig: `${sig.slice(0, -4)}dead`,
  });
  assert.equal(isForgedValid, false);
});

